# Generated by Django 3.0.7 on 2020-06-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='question',
            field=models.CharField(default='default', max_length=250),
            preserve_default=False,
        ),
    ]
